apiVersion: apps/v1
kind: Deployment
metadata:
  name: imerspa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imerspa
  template:
    metadata:
      labels:
        app: imerspa
    spec:
      containers:
      - name: imerspa
        image: 192.168.1.181:30002/imer/imerspa:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor-secret
