apiVersion: apps/v1
kind: Deployment
metadata:
  name: imerpub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: imerpub
  template:
    metadata:
      labels:
        app: imerpub
    spec:
      containers:
      - name: imerpub
        image: 192.168.1.181:30002/imer/imerpub:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor-secret
