apiVersion: apps/v1
kind: Deployment
metadata:
  name: napoliscc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: napoliscc
  template:
    metadata:
      labels:
        app: napoliscc
    spec:
      containers:
      - name: napoliscc
        image: 192.168.1.181:30002/imer/napoliscc:v3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor-secret
