apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: napoliscc-ingress
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - napoliscc.internal
    secretName: tls-certificate
  rules:
  - host: napoliscc.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: napoliscc-service
            port:
              number: 80

